void setup() {
    int volume = 20;
    int mult = 4;
    int des = 742;
    pinMode(D4,INPUT);
    while (digitalRead(D4)==LOW){
        delayMicroseconds(1);
    }
    pinMode(D2,OUTPUT);
    analogWrite(D2,0, 40);
    delayMicroseconds(1918*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(3840*des);
    analogWrite(D2,0, 40);
    delayMicroseconds(2*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(3840*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(73*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(167*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 38);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 38);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 38);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 37);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 37);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 37);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 33);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 33);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(720*des);
    analogWrite(D2,volume, 31*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 31*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 31*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(720*des);
    analogWrite(D2,volume, 31*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 31*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 31*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 44*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 39*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 44*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 39*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 39*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 42*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 43*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 42*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 45*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,0, 40);
    delayMicroseconds(1200*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(18*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 39*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 42*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 38);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 38);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 38);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 37);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 37);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 37);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 33);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 33);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(720*des);
    analogWrite(D2,volume, 31*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 31*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 31*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(720*des);
    analogWrite(D2,volume, 31*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 31*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 31*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 44*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 39*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 44*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 39*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 39*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 42*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 43*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 42*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 45*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,0, 40);
    delayMicroseconds(1200*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(18*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 39*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 42*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 31*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 31*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 31*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 31*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 31*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 31*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,0, 36);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(3600*des);
    analogWrite(D2,volume, 49*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(3840*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 39*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(3600*des);
    analogWrite(D2,volume, 49*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(3840*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 30*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 34*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 34*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 34*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 34*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 34*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 34*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 34*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 34*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,0, 40);
    delayMicroseconds(1200*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(18*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 39*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 42*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 39*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 42*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 40*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(480*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 36*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 28);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 28*mult);
    delayMicroseconds(180*des);
    analogWrite(D2,0, 38);
    delayMicroseconds(60*des);
    analogWrite(D2,volume, 38*mult);
    delayMicroseconds(720*des);
    analogWrite(D2,volume, 37*mult);
    delayMicroseconds(720*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(2400*des);
    analogWrite(D2,volume, 32*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 33*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 35*mult);
    delayMicroseconds(240*des);
    analogWrite(D2,volume, 127*mult);
    delayMicroseconds(1*des);
    analogWrite(D2,0, 0);
}

void loop() {

}